# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/wst24365888/SynologyDrive/NYCU/master_1111/numerical_software_development/libstreamvbyte

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/wst24365888/SynologyDrive/NYCU/master_1111/numerical_software_development/libstreamvbyte

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/wst24365888/SynologyDrive/NYCU/master_1111/numerical_software_development/libstreamvbyte/CMakeFiles /mnt/c/Users/wst24365888/SynologyDrive/NYCU/master_1111/numerical_software_development/libstreamvbyte//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/wst24365888/SynologyDrive/NYCU/master_1111/numerical_software_development/libstreamvbyte/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libstreamvbyte

# Build rule for target.
libstreamvbyte: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libstreamvbyte
.PHONY : libstreamvbyte

# fast build rule for target.
libstreamvbyte/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/build
.PHONY : libstreamvbyte/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

libstreamvbyte/decode/decode.o: libstreamvbyte/decode/decode.cpp.o
.PHONY : libstreamvbyte/decode/decode.o

# target to build an object file
libstreamvbyte/decode/decode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/decode/decode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/libstreamvbyte/decode/decode.cpp.o
.PHONY : libstreamvbyte/decode/decode.cpp.o

libstreamvbyte/decode/decode.i: libstreamvbyte/decode/decode.cpp.i
.PHONY : libstreamvbyte/decode/decode.i

# target to preprocess a source file
libstreamvbyte/decode/decode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/decode/decode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/libstreamvbyte/decode/decode.cpp.i
.PHONY : libstreamvbyte/decode/decode.cpp.i

libstreamvbyte/decode/decode.s: libstreamvbyte/decode/decode.cpp.s
.PHONY : libstreamvbyte/decode/decode.s

# target to generate assembly for a file
libstreamvbyte/decode/decode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/decode/decode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/libstreamvbyte/decode/decode.cpp.s
.PHONY : libstreamvbyte/decode/decode.cpp.s

libstreamvbyte/encode/encode.o: libstreamvbyte/encode/encode.cpp.o
.PHONY : libstreamvbyte/encode/encode.o

# target to build an object file
libstreamvbyte/encode/encode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/encode/encode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/libstreamvbyte/encode/encode.cpp.o
.PHONY : libstreamvbyte/encode/encode.cpp.o

libstreamvbyte/encode/encode.i: libstreamvbyte/encode/encode.cpp.i
.PHONY : libstreamvbyte/encode/encode.i

# target to preprocess a source file
libstreamvbyte/encode/encode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/encode/encode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/libstreamvbyte/encode/encode.cpp.i
.PHONY : libstreamvbyte/encode/encode.cpp.i

libstreamvbyte/encode/encode.s: libstreamvbyte/encode/encode.cpp.s
.PHONY : libstreamvbyte/encode/encode.s

# target to generate assembly for a file
libstreamvbyte/encode/encode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/encode/encode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/libstreamvbyte/encode/encode.cpp.s
.PHONY : libstreamvbyte/encode/encode.cpp.s

libstreamvbyte/streamvbyte.o: libstreamvbyte/streamvbyte.cpp.o
.PHONY : libstreamvbyte/streamvbyte.o

# target to build an object file
libstreamvbyte/streamvbyte.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/streamvbyte.cpp.o
.PHONY : libstreamvbyte/streamvbyte.cpp.o

libstreamvbyte/streamvbyte.i: libstreamvbyte/streamvbyte.cpp.i
.PHONY : libstreamvbyte/streamvbyte.i

# target to preprocess a source file
libstreamvbyte/streamvbyte.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/streamvbyte.cpp.i
.PHONY : libstreamvbyte/streamvbyte.cpp.i

libstreamvbyte/streamvbyte.s: libstreamvbyte/streamvbyte.cpp.s
.PHONY : libstreamvbyte/streamvbyte.s

# target to generate assembly for a file
libstreamvbyte/streamvbyte.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libstreamvbyte.dir/build.make CMakeFiles/libstreamvbyte.dir/libstreamvbyte/streamvbyte.cpp.s
.PHONY : libstreamvbyte/streamvbyte.cpp.s

tests/test.o: tests/test.cpp.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... libstreamvbyte"
	@echo "... test"
	@echo "... libstreamvbyte/decode/decode.o"
	@echo "... libstreamvbyte/decode/decode.i"
	@echo "... libstreamvbyte/decode/decode.s"
	@echo "... libstreamvbyte/encode/encode.o"
	@echo "... libstreamvbyte/encode/encode.i"
	@echo "... libstreamvbyte/encode/encode.s"
	@echo "... libstreamvbyte/streamvbyte.o"
	@echo "... libstreamvbyte/streamvbyte.i"
	@echo "... libstreamvbyte/streamvbyte.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

